name: Macos Release
on:
  workflow_dispatch:



jobs:
  Version:
    runs-on: windows-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4.1.5

      - name: Extract version from pubspec yaml
        id: extract_version
        run: |
          $VERSION = Select-String  -Path ".\pubspec.yaml" -Pattern "version: (\d+\.\d+\.\d+)" -CaseSensitive | ForEach-Object{ $_.Matches.Groups[1].Value }
          echo version=$VERSION >> $env:GITHUB_OUTPUT

  Build-macos:
    runs-on: macos-latest
    permissions:
      contents: read
    needs: Version
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.5

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - name: Print Environment Info
        run: |
          echo "--- Flutter Version --- "
          flutter --version --verbose
          echo "--- Dart Version --- "
          dart --version
          echo "--- macOS Version --- "
          sw_vers
          echo "--- Xcode Version --- "
          xcodebuild -version
          echo "--- Xcode SDKs --- "
          xcodebuild -showsdks
          echo "--- CocoaPods Version --- "
          pod --version
          echo "--- Node Version --- "
          node --version
          echo "--- npm Version --- "
          npm --version
          echo "--- Ruby Version --- "
          ruby --version
          echo "--- RubyGems Version --- "
          gem --version
          echo "--- System Info --- "
          uname -a
          echo "--- pubspec.lock loader_overlay --- "
          grep loader_overlay pubspec.lock | cat
          echo "--- Flutter Pub Deps --- "
          flutter pub deps

      - name: Display Flutter and Dart version
        run: |
          flutter --version
          dart --version

      - name: Enable macos desktop for flutter
        run: flutter config --enable-macos-desktop && export PATH="$PATH":"$HOME/.pub-cache/bin"

      - name: Ensure macos directory exists
        run: flutter create --platform macos .

      - name: Remove RunnerTests target from Podfile
        run: |
          echo "Attempting to remove RunnerTests target from Podfile using awk..."
          awk '/^target \'\'\'RunnerTests\'\'\' do/ { skip=1 } !skip; /^end/ && skip { skip=0; next }' macos/Podfile > macos/Podfile.tmp && mv macos/Podfile.tmp macos/Podfile
          echo "--- Podfile after attempting removal --- "
          cat macos/Podfile

      - name: Get dependencies
        run: flutter pub get

      - name: Install flutter distributor
        run: dart pub global activate flutter_distributor

      - name: Start the build process
        run: flutter_distributor package --platform macos --targets dmg

      - name: Rename dmg file
        run: mv dist/${{ needs.version.outputs.version }}/brisk-${{ needs.version.outputs.version }}+${{ needs.version.outputs.version }}-macos.dmg ./Brisk-${{ needs.version.outputs.version }}-macos-x64.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: brisk-dmg
          path: Brisk-${{ needs.version.outputs.version }}-macos-x64.dmg
          retention-days: 1


  Release:
    runs-on: ubuntu-latest
    needs: [Build-macos, Version]
    permissions:
      contents: write
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4.1.5

      - name: Download artifact package
        uses: actions/download-artifact@v4.1.0
        with:
          name: brisk-dmg

      - name: List files
        run: ls .

      - name: Release the changes
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.version.outputs.version }}
          body_path: ./.github/release.md
          files: ./Brisk-${{ needs.version.outputs.version }}-macos-x64.dmg



